version: '3.8'
services:
  database:
    image: postgres:15
    container_name: ticket_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tickets
    ports:
      - "5432:5432"
